### ISSUE TITLE
除了if print isnil 还支持哪些语法挖

### ISSUE THREAD

**Issue by ayamzh** [bilibili/gengine#10]
switch case  for  while  之类的支持么？？

**Comment by rencalo770** [comment]
switch,for, while不支持;所有的支持语法都在附带的wiki中有说明,欢迎查看哦

**Comment by ayamzh** [comment]
看了下，例子很少，只见到了if和赋值。。没别的语法了是吧？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月14日(周五) 晚上11:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bilibili/gengine] 除了if print isnil 还支持哪些语法挖 (#10)




 
switch,for, while不支持;所有的支持语法都在附带的wiki中有说明,欢迎查看哦

**Comment by rencalo770** [comment]
这样理解也是可以的。规则需要在界面手写配置的，不像当前流行语言，有各种开发工具支持避免语法错误，所以我们的设计初衷就是在满足需求的情况下力求语法简单。而且任何不能直接在规则层面直接书写的，都可以用函数包装之后注入实现。
