### ISSUE TITLE
CGO_ENABLED=0 GOOS=linux GOARCH=arm go build int overflow

### ISSUE THREAD

**Issue by styfstr** [bilibili/gengine#14]
# github.com/bilibili/gengine/internal/iantlr/alr
D:\gopath\pkg\mod\github.com\bilibili\gengine@v1.5.6\internal\iantlr\alr\gengine_parser.go:5415:221: constant 4227858432 overflows int

**Comment by rencalo770** [comment]
这个试试？（try this？）
https://blog.csdn.net/feiwutudou/article/details/83652790

**Comment by styfstr** [comment]
一样的错误
![image](https://user-images.githubusercontent.com/44523785/123066455-abc9ef00-d442-11eb-9bc5-97da67b5994b.png)

**Comment by styfstr** [comment]
问题已经解决，将数据类型做了转换

![image](https://user-images.githubusercontent.com/44523785/123075206-9953b380-d44a-11eb-9c8a-57a95776debd.png)
