### ISSUE TITLE
规则构建耗时异常

### ISSUE THREAD

**Issue by ychencode** [bilibili/gengine#16]
我有一个规则，规则的字符串如下：
code := `rule "weight_rule" "weight_rule" salience 0
begin
return ((1 * (1 + data.UpvoteNum) / (5.19 + data.CardShow)) +
		10*(1+data.UpvoteNum)/(317.65+data.CardShow) +
		5*(1+data.CollectNum)/(797.57+data.CardShow) +
		0*(1+data.ShareNum)/(4790.89+data.CardShow) +
		10*(1+data.ThankNum)/(1585.75+data.CardShow) +
		25*(1+data.CommentNum)/(3465.75+data.CardShow) +
		60*(1+data.AnswerNum)/(11097.10+data.CardShow) +
		-40*(1+data.VoteDownNum)/(9400.99+data.CardShow) +
		35*(1+data.FollowNum)/(2986.13+data.CardShow)) * Sigmoid(Log10N(data.CardShow/50))
end`
然后我通过引擎池去执行这个规则
enginePool, err := engine.NewGenginePool(1, 10, 2, code, map[string]interface{}{
		"Sigmoid": Sigmoid,
		"Log10N":  Log10N,
	})
if err != nil {
	panic(err)
}
err, resultMap := enginePool.Execute(map[string]interface{}{
	"data": contentAggregateData,
}, false)
if err != nil {
	panic(err)
}
我发现，在第一步解析规则字符串的时候耗时非常高，大约要3min以上才能完成

**Comment by rencalo770** [comment]
首先，得赞扬大哥“好身手”，能把这么长的代码(规则)直接一个return给“收了”，而且还没有语法错误😂👍
你这样写，的确会使编译时间变得非常长，在差点的笔记本上编译估计要花3分钟（如你所测得的），在好点的笔记本上编译也要花个100秒左右。
之所以会发生这种编译性能变得超级慢的原因是，你将规则语法写在了一行之后，导致语法树是一棵深度是30多的多叉树，因此导致编译速度变得超级慢。具体可视化如下
![image](https://user-images.githubusercontent.com/58161376/127180252-9663baee-f376-463f-a012-6ccb77aedc19.png)
-------------------------------------
通常而言，代码(规则),无论是工程级的，还是函数级的，都应该是模块化的，这样即使没有大哥这般“好身手”，书写复杂的实现也不会出错，所以我给出的你的这个规则的优化如下：
`
rule "weight_rule" "weight_rule" salience 0 
begin
 a = 1 * (1 + data.UpvoteNum) / (5.19 + data.CardShow)
 b = 10*(1+data.UpvoteNum)/(317.65+data.CardShow) 
 c = 5*(1+data.CollectNum)/(797.57+data.CardShow)
 d = 0*(1+data.ShareNum)/(4790.89+data.CardShow) //我从这里看出你就是来测试语法的，哈哈
 e = 10*(1+data.ThankNum)/(1585.75+data.CardShow) 
 f = 25*(1+data.CommentNum)/(3465.75+data.CardShow) 
 g = 60*(1+data.AnswerNum)/(11097.10+data.CardShow)
 h = -40*(1+data.VoteDownNum)/(9400.99+data.CardShow)
 i = 35*(1+data.FollowNum)/(2986.13+data.CardShow) 
 j	= Sigmoid(Log10N(data.CardShow/50))
 return (a + b + c + d + e + f + g + h + i) * j 
end
`
这样优化之后，编译时长可以降低至30毫秒，如下所示：
![image](https://user-images.githubusercontent.com/58161376/127180468-e2c383eb-d6ed-4942-ae1f-83398d90b208.png)

**Comment by ychencode** [comment]
hhhh, thank you

**Comment by gopkg-dev** [comment]
秀儿啊 哈哈
