### ISSUE TITLE
最佳实践里的MyService是一个业务请求新建一次吗？

### ISSUE THREAD

**Issue by Jun10ng** [bilibili/gengine#39]
hi team,
我想请问下, 我对 wiki里的[最佳实践](https://github.com/bilibili/gengine/wiki/%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5)一节有个疑问，这里的MyService是一个业务请求新建一次，还是所有业务请求共用一个MyService？
![image](https://user-images.githubusercontent.com/46768176/148488278-6c89c3a4-aae0-4da0-8b54-6ae55cb8db79.png)

**Comment by CxcPDF** [comment]
我理解应该是用一个，共用一个pool
