### ISSUE TITLE
gengine的DSL语法不支持接收函数的多个返回参数吗？

### ISSUE THREAD

**Issue by studentTxl** [bilibili/gengine#4]
写了一个规则引擎的插件，使用的时候发现gengine的DSL语法只支持一个接收一个参数，对于go这种语言多返回值的时候，很难处理

**Comment by Lynnworld** [comment]
是的，为了保持语法的简洁只支持单值返回。

**Comment by kamly** [comment]
@studentTxl 可以试下传入 struct ？

**Comment by rencalo770** [comment]
> @studentTxl 可以试下传入 struct ？

对的。其实返回多个值其实并不是必须的，仅需要返回一个包装类型的结构（如struct），就可以在struct内返回任意多个值。

**Comment by studentTxl** [comment]
是的 可以这样处理

**Comment by studentTxl** [comment]
> > @studentTxl 可以试下传入 struct ？
> 
> 对的。其实返回多个值其实并不是必须的，仅需要返回一个包装类型的结构（如struct），就可以在struct内返回任意多个值。

是的 可以这样处理
