### ISSUE TITLE
rule执行go的function时，支持返回多个值吗？

### ISSUE THREAD

**Issue by Little-Timo** [bilibili/gengine#58]
比如go的一个函数myFunc，在入rule映射为MyFunc：
```go
func myFunc()(int, string){
}
```

在rule中应用：
```rule
rule "ruleId"
begin
    a, str := MyFunc()
    Print(str)
end
```

实际在执行rule的过程中，只能拿到a的值，str的值是拿不到的吗，后续能支持吗

**Comment by johnyanchen** [comment]
啊，这个不支持返回多个值？

**Comment by johnyanchen** [comment]
<img width="702" alt="image" src="https://github.com/bilibili/gengine/assets/18901784/4bf7aee1-8750-455a-933f-ed5755c27e73">
除非改代码

**Comment by littetimo567** [comment]
感觉不是这个意思+_+，是在rule自己的函数拿不到多个返回
