### ISSUE TITLE
停止标志位和return不能同时使用？

### ISSUE THREAD

**Issue by guoxf** [bilibili/gengine#6]

**Comment by rencalo770** [comment]
可以同时使用。停止标志位是规则之间的执行控制符，return是规则内的停止控制符。

**Comment by guoxf** [comment]
我试了先stop，然后在return，获取不到return的数据。

使用的版本是v1.5.4

**Comment by rencalo770** [comment]
获取的是stop之前的规则return，还是获取stop之后的规则return

**Comment by guoxf** [comment]
> 获取的是stop之前的规则return，还是获取stop之后的规则return

stop之后的规则return

**Comment by rencalo770** [comment]
stop之后的规则是不会被执行的，因为你已经将他们stop了。所以，你只能获取stop之前的规则的return结果

**Comment by guoxf** [comment]
> stop之后的规则是不会被执行的，因为你已经将他们stop了。所以，你只能获取stop之前的规则的return结果

好的，谢谢！
