### ISSUE TITLE
dataContext.Add 参数实际传入类型为int64，引擎调用本地函数签名类型也为int64，但引擎应该是作为float进行处理，导致出现精度问题，这个问题能解决下么？

### ISSUE THREAD

**Issue by bravesmiles** [bilibili/gengine#7]
dataContext.Add 参数实际传入类型为int64，引擎调用本地函数签名类型也为int64，但引擎应该是作为float进行处理，导致出现精度问题，这个问题能解决下么？

**Comment by rencalo770** [comment]
因为gengine的计算特性和golang是保持一致的，但你所说的也的确有道理。容我重新测试测试，看看如何处理你提的这个问题

**Comment by bravesmiles** [comment]
> 因为gengine的计算特性和golang是保持一致的，但你所说的也的确有道理。容我重新测试测试，看看如何处理你提的这个问题

感谢，关于引擎有些问题也想跟你请教下，不知道能不能方便加个微信？

**Comment by rencalo770** [comment]
嗯，加了
