### ISSUE TITLE
是否有计划集成图形拖拽界面

### ISSUE THREAD

**Issue by wanglihui** [bilibili/gengine#9]
是否有计划集成图形拖拽界面,例如像 drools 集成的 JBPM ?  虽然引擎语言比golang稍微好理解些，但是还不具备让业务方直接拖拽配置

**Comment by rencalo770** [comment]
在计划中了，但是需要花点时间去支持

**Comment by rencalo770** [comment]
正在开发中了，预计最少支持两种模式的界面规则编辑

**Comment by lexee** [comment]
UI好呀，让业务方写规则code估计接受度不高的
